server:
  port: 8000

bot:
  webhook-path: https://7a3f-194-226-248-0.eu.ngrok.io
  token: 6059530887:AAFHPmDyT_obKiD-uI2TSUMGnRzSV-n11PE
  name: Weatherfy
  most-popular-cities: Екатеринбург,Москва,Санкт Петербург,Казань,Краснодар

weatherApi:
  protocol: https
  host: api.openweathermap.org
  weatherEndpoint: /data/2.5/weather
  forecastEndpoint: /data/2.5/forecast
  geoEndpoint: /geo/1.0/direct
  token: b3aad3b9c2d7988afae46a7f1973b6d7
  units: metric

spring:
  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update

