server:
  weather-cache-evict-cron: 0 0 0/3 * * ?
  quota-refresh-cron: 0 13 17 * * ?
  port: 8000

bot:
  webhook-path: https://c939-193-168-176-146.ngrok-free.app
  token: 6049421309:AAFcsBO-Fa5SX62QCSpaqu82wO4ff-BJiMk
  name: Weatherfy dev
  most-popular-cities: Екатеринбург,Москва,Санкт Петербург,Казань,Краснодар

weatherApi:
  protocol: http
  host: api.openweathermap.org
  weatherEndpoint: /data/2.5/weather
  forecastEndpoint: /data/2.5/forecast
  geoEndpoint: /geo/1.0/direct
  token: b3aad3b9c2d7988afae46a7f1973b6d7
  units: metric
  forecastStepInHours: 3
  timestamps-in-api-response: 40
